/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EventData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_EventData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EventData(SWIGTYPE_p_mlt_event_data arg0) {
    this(mltJNI.new_EventData__SWIG_0(SWIGTYPE_p_mlt_event_data.getCPtr(arg0)), true);
  }

  public EventData(EventData arg0) {
    this(mltJNI.new_EventData__SWIG_1(EventData.getCPtr(arg0), arg0), true);
  }

  public SWIGTYPE_p_mlt_event_data get_event_data() {
    return new SWIGTYPE_p_mlt_event_data(mltJNI.EventData_get_event_data(swigCPtr, this), true);
  }

  public int to_int() {
    return mltJNI.EventData_to_int(swigCPtr, this);
  }

  public String to_string() {
    return mltJNI.EventData_to_string(swigCPtr, this);
  }

  public Frame to_frame() {
    return new Frame(mltJNI.EventData_to_frame(swigCPtr, this), true);
  }

  public SWIGTYPE_p_void to_object() {
    long cPtr = mltJNI.EventData_to_object(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
