/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class mlt_colorspace {
  public final static mlt_colorspace mlt_colorspace_rgb = new mlt_colorspace("mlt_colorspace_rgb", mltJNI.mlt_colorspace_rgb_get());
  public final static mlt_colorspace mlt_colorspace_bt709 = new mlt_colorspace("mlt_colorspace_bt709", mltJNI.mlt_colorspace_bt709_get());
  public final static mlt_colorspace mlt_colorspace_unspecified = new mlt_colorspace("mlt_colorspace_unspecified", mltJNI.mlt_colorspace_unspecified_get());
  public final static mlt_colorspace mlt_colorspace_reserved = new mlt_colorspace("mlt_colorspace_reserved", mltJNI.mlt_colorspace_reserved_get());
  public final static mlt_colorspace mlt_colorspace_fcc = new mlt_colorspace("mlt_colorspace_fcc", mltJNI.mlt_colorspace_fcc_get());
  public final static mlt_colorspace mlt_colorspace_bt470bg = new mlt_colorspace("mlt_colorspace_bt470bg", mltJNI.mlt_colorspace_bt470bg_get());
  public final static mlt_colorspace mlt_colorspace_smpte170m = new mlt_colorspace("mlt_colorspace_smpte170m", mltJNI.mlt_colorspace_smpte170m_get());
  public final static mlt_colorspace mlt_colorspace_smpte240m = new mlt_colorspace("mlt_colorspace_smpte240m", mltJNI.mlt_colorspace_smpte240m_get());
  public final static mlt_colorspace mlt_colorspace_ycgco = new mlt_colorspace("mlt_colorspace_ycgco", mltJNI.mlt_colorspace_ycgco_get());
  public final static mlt_colorspace mlt_colorspace_bt2020_ncl = new mlt_colorspace("mlt_colorspace_bt2020_ncl", mltJNI.mlt_colorspace_bt2020_ncl_get());
  public final static mlt_colorspace mlt_colorspace_bt2020_cl = new mlt_colorspace("mlt_colorspace_bt2020_cl", mltJNI.mlt_colorspace_bt2020_cl_get());
  public final static mlt_colorspace mlt_colorspace_smpte2085 = new mlt_colorspace("mlt_colorspace_smpte2085", mltJNI.mlt_colorspace_smpte2085_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_colorspace swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_colorspace.class + " with value " + swigValue);
  }

  private mlt_colorspace(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_colorspace(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_colorspace(String swigName, mlt_colorspace swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_colorspace[] swigValues = { mlt_colorspace_rgb, mlt_colorspace_bt709, mlt_colorspace_unspecified, mlt_colorspace_reserved, mlt_colorspace_fcc, mlt_colorspace_bt470bg, mlt_colorspace_smpte170m, mlt_colorspace_smpte240m, mlt_colorspace_ycgco, mlt_colorspace_bt2020_ncl, mlt_colorspace_bt2020_cl, mlt_colorspace_smpte2085 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

