package mltJNI;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class mlt_deinterlacer {
  public final static mlt_deinterlacer mlt_deinterlacer_none = new mlt_deinterlacer("mlt_deinterlacer_none");
  public final static mlt_deinterlacer mlt_deinterlacer_onefield = new mlt_deinterlacer("mlt_deinterlacer_onefield");
  public final static mlt_deinterlacer mlt_deinterlacer_linearblend = new mlt_deinterlacer("mlt_deinterlacer_linearblend");
  public final static mlt_deinterlacer mlt_deinterlacer_weave = new mlt_deinterlacer("mlt_deinterlacer_weave");
  public final static mlt_deinterlacer mlt_deinterlacer_bob = new mlt_deinterlacer("mlt_deinterlacer_bob");
  public final static mlt_deinterlacer mlt_deinterlacer_greedy = new mlt_deinterlacer("mlt_deinterlacer_greedy");
  public final static mlt_deinterlacer mlt_deinterlacer_yadif_nospatial = new mlt_deinterlacer("mlt_deinterlacer_yadif_nospatial");
  public final static mlt_deinterlacer mlt_deinterlacer_yadif = new mlt_deinterlacer("mlt_deinterlacer_yadif");
  public final static mlt_deinterlacer mlt_deinterlacer_bwdif = new mlt_deinterlacer("mlt_deinterlacer_bwdif");
  public final static mlt_deinterlacer mlt_deinterlacer_estdif = new mlt_deinterlacer("mlt_deinterlacer_estdif");
  public final static mlt_deinterlacer mlt_deinterlacer_invalid = new mlt_deinterlacer("mlt_deinterlacer_invalid");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_deinterlacer swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_deinterlacer.class + " with value " + swigValue);
  }

  private mlt_deinterlacer(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_deinterlacer(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_deinterlacer(String swigName, mlt_deinterlacer swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_deinterlacer[] swigValues = { mlt_deinterlacer_none, mlt_deinterlacer_onefield, mlt_deinterlacer_linearblend, mlt_deinterlacer_weave, mlt_deinterlacer_bob, mlt_deinterlacer_greedy, mlt_deinterlacer_yadif_nospatial, mlt_deinterlacer_yadif, mlt_deinterlacer_bwdif, mlt_deinterlacer_estdif, mlt_deinterlacer_invalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

