/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class mlt_service_type {
  public final static mlt_service_type mlt_service_invalid_type = new mlt_service_type("mlt_service_invalid_type", mltJNI.mlt_service_invalid_type_get());
  public final static mlt_service_type mlt_service_unknown_type = new mlt_service_type("mlt_service_unknown_type");
  public final static mlt_service_type mlt_service_producer_type = new mlt_service_type("mlt_service_producer_type");
  public final static mlt_service_type mlt_service_tractor_type = new mlt_service_type("mlt_service_tractor_type");
  public final static mlt_service_type mlt_service_playlist_type = new mlt_service_type("mlt_service_playlist_type");
  public final static mlt_service_type mlt_service_multitrack_type = new mlt_service_type("mlt_service_multitrack_type");
  public final static mlt_service_type mlt_service_filter_type = new mlt_service_type("mlt_service_filter_type");
  public final static mlt_service_type mlt_service_transition_type = new mlt_service_type("mlt_service_transition_type");
  public final static mlt_service_type mlt_service_consumer_type = new mlt_service_type("mlt_service_consumer_type");
  public final static mlt_service_type mlt_service_field_type = new mlt_service_type("mlt_service_field_type");
  public final static mlt_service_type mlt_service_link_type = new mlt_service_type("mlt_service_link_type");
  public final static mlt_service_type mlt_service_chain_type = new mlt_service_type("mlt_service_chain_type");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_service_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_service_type.class + " with value " + swigValue);
  }

  private mlt_service_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_service_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_service_type(String swigName, mlt_service_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_service_type[] swigValues = { mlt_service_invalid_type, mlt_service_unknown_type, mlt_service_producer_type, mlt_service_tractor_type, mlt_service_playlist_type, mlt_service_multitrack_type, mlt_service_filter_type, mlt_service_transition_type, mlt_service_consumer_type, mlt_service_field_type, mlt_service_link_type, mlt_service_chain_type };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

