//
// Created by huihui on 2023/10/11.
//

#ifndef VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_CHAIN_RENDERCHAIN_H
#define VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_CHAIN_RENDERCHAIN_H

namespace RenderEngine {

class RenderChain {

};

} // RenderEngine

#endif //VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_CHAIN_RENDERCHAIN_H
