/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.huihui.videoedit.mlt;

public final class mlt_channel_layout {
  public final static mlt_channel_layout mlt_channel_auto = new mlt_channel_layout("mlt_channel_auto", mltJNI.mlt_channel_auto_get());
  public final static mlt_channel_layout mlt_channel_independent = new mlt_channel_layout("mlt_channel_independent");
  public final static mlt_channel_layout mlt_channel_mono = new mlt_channel_layout("mlt_channel_mono");
  public final static mlt_channel_layout mlt_channel_stereo = new mlt_channel_layout("mlt_channel_stereo");
  public final static mlt_channel_layout mlt_channel_2p1 = new mlt_channel_layout("mlt_channel_2p1");
  public final static mlt_channel_layout mlt_channel_3p0 = new mlt_channel_layout("mlt_channel_3p0");
  public final static mlt_channel_layout mlt_channel_3p0_back = new mlt_channel_layout("mlt_channel_3p0_back");
  public final static mlt_channel_layout mlt_channel_4p0 = new mlt_channel_layout("mlt_channel_4p0");
  public final static mlt_channel_layout mlt_channel_quad_back = new mlt_channel_layout("mlt_channel_quad_back");
  public final static mlt_channel_layout mlt_channel_quad_side = new mlt_channel_layout("mlt_channel_quad_side");
  public final static mlt_channel_layout mlt_channel_3p1 = new mlt_channel_layout("mlt_channel_3p1");
  public final static mlt_channel_layout mlt_channel_5p0_back = new mlt_channel_layout("mlt_channel_5p0_back");
  public final static mlt_channel_layout mlt_channel_5p0 = new mlt_channel_layout("mlt_channel_5p0");
  public final static mlt_channel_layout mlt_channel_4p1 = new mlt_channel_layout("mlt_channel_4p1");
  public final static mlt_channel_layout mlt_channel_5p1_back = new mlt_channel_layout("mlt_channel_5p1_back");
  public final static mlt_channel_layout mlt_channel_5p1 = new mlt_channel_layout("mlt_channel_5p1");
  public final static mlt_channel_layout mlt_channel_6p0 = new mlt_channel_layout("mlt_channel_6p0");
  public final static mlt_channel_layout mlt_channel_6p0_front = new mlt_channel_layout("mlt_channel_6p0_front");
  public final static mlt_channel_layout mlt_channel_hexagonal = new mlt_channel_layout("mlt_channel_hexagonal");
  public final static mlt_channel_layout mlt_channel_6p1 = new mlt_channel_layout("mlt_channel_6p1");
  public final static mlt_channel_layout mlt_channel_6p1_back = new mlt_channel_layout("mlt_channel_6p1_back");
  public final static mlt_channel_layout mlt_channel_6p1_front = new mlt_channel_layout("mlt_channel_6p1_front");
  public final static mlt_channel_layout mlt_channel_7p0 = new mlt_channel_layout("mlt_channel_7p0");
  public final static mlt_channel_layout mlt_channel_7p0_front = new mlt_channel_layout("mlt_channel_7p0_front");
  public final static mlt_channel_layout mlt_channel_7p1 = new mlt_channel_layout("mlt_channel_7p1");
  public final static mlt_channel_layout mlt_channel_7p1_wide_side = new mlt_channel_layout("mlt_channel_7p1_wide_side");
  public final static mlt_channel_layout mlt_channel_7p1_wide_back = new mlt_channel_layout("mlt_channel_7p1_wide_back");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_channel_layout swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_channel_layout.class + " with value " + swigValue);
  }

  private mlt_channel_layout(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_channel_layout(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_channel_layout(String swigName, mlt_channel_layout swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_channel_layout[] swigValues = { mlt_channel_auto, mlt_channel_independent, mlt_channel_mono, mlt_channel_stereo, mlt_channel_2p1, mlt_channel_3p0, mlt_channel_3p0_back, mlt_channel_4p0, mlt_channel_quad_back, mlt_channel_quad_side, mlt_channel_3p1, mlt_channel_5p0_back, mlt_channel_5p0, mlt_channel_4p1, mlt_channel_5p1_back, mlt_channel_5p1, mlt_channel_6p0, mlt_channel_6p0_front, mlt_channel_hexagonal, mlt_channel_6p1, mlt_channel_6p1_back, mlt_channel_6p1_front, mlt_channel_7p0, mlt_channel_7p0_front, mlt_channel_7p1, mlt_channel_7p1_wide_side, mlt_channel_7p1_wide_back };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

