/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.huihui.videoedit.mlt;

public class SWIGTYPE_p_mlt_image_format {
  private transient long swigCPtr;

  protected SWIGTYPE_p_mlt_image_format(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_mlt_image_format() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_mlt_image_format obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

