//
// Created by huihui on 2023/10/11.
//

#ifndef VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_RENDER_GLCONTEXT_H
#define VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_RENDER_GLCONTEXT_H

namespace RenderEngine {

class GLContext {

};

} // RenderEngine

#endif //VIDEOEDIT_APP_SRC_MAIN_CPP_RENDERENGINE_RENDER_GLCONTEXT_H
